# Generated by Django 2.2.6 on 2019-11-04 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191104_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 276098, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 276098, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='size',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 275098, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='size',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 275098, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='subextra',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 275098, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='subextra',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 275098, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='topping',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 275098, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='topping',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 275098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 274099, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 42, 5, 274099, tzinfo=utc)),
        ),
    ]
