# Generated by Django 2.2.6 on 2019-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
        ('orders', '0004_auto_20191021_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='pizza.SubExtra'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='pizza.SubExtra'),
        ),
    ]
