# Generated by Django 2.2.6 on 2019-11-04 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191022_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 761001, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 761001, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 758998, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 758998, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 760001, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 760001, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderstatuscode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 758998, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='orderstatuscode',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 46, 59, 758998, tzinfo=utc)),
        ),
    ]
